server:
  port: 14520
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  servlet:
    context-path: /xiaojin-boot

jasypt:
  encryptor:
    property:
      prefix: CODE#
      suffix: #